Controllers/ActorsController.cs
using Ecommerce.Data;
using Ecommerce.Data.RequestHandlers.ActorsRequestHandlers;
using Ecommerce.Data.Services;
using Ecommerce.Models;
using Ecommerce.Models.Validators.ActorValidators;
using FluentValidation;
using FluentValidation.Results;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;

namespace Ecommerce.Controllers
{
    public class ActorsController : Controller
    {
        private readonly ISender _actorsService;
        public ActorsController(ISender actorsService)
        {
            _actorsService = actorsService;

        }
        public async Task<IActionResult> Index()
        {
            var response = await _actorsService.Send(new GetActors());



            return View(response);
        }

        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Actors actor)

        {
            ActorValidator actorsValidator = new ActorValidator();
            ValidationResult result = await actorsValidator.ValidateAsync(actor);
            if (!result.IsValid)
            {
                foreach (var failure in result.Errors)
                {
                    //ModelState.AddModelError(failure.ErrorCode, failure.ErrorMessage);
                    ModelState.AddModelError(failure.PropertyName, failure.ErrorMessage);
                }
                return View(actor);
            }

            await _actorsService.Send(new AddActor { actors = actor});

            return RedirectToAction(nameof(Index));

        }

        public async Task<IActionResult> Details(int id)
        {
            var query = new GetActorById { Id = id };
            var newGetActorByIdValidator = new GetActorByIdValidator(id);
            var result = await newGetActorByIdValidator.ValidateAsync(query);

            if (!result.IsValid)
            {
                return RedirectToAction(nameof(Index));
            }
            var actorDetails = await _actorsService.Send(query);

            if(actorDetails == null) {
                return RedirectToAction(nameof(Index));

            }
            return View(actorDetails);

        }
        public async Task<IActionResult> Edit(int id)
        {
            var query = new GetActorById { Id = id };
            var newGetActorByIdValidator = new GetActorByIdValidator(id);
            var result = await newGetActorByIdValidator.ValidateAsync(query);

            if (!result.IsValid)
            {
                return RedirectToAction(nameof(NotFound));
            }
            var actorDetails = await _actorsService.Send(query);

            if (actorDetails == null)
            {
                return RedirectToAction(nameof(Index));

            }
            return View(actorDetails);

        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id,Actors actor)

        {
            ActorValidator actorsValidator = new ActorValidator();
            ValidationResult result = await actorsValidator.ValidateAsync(actor);
            if (!result.IsValid)
            {
                foreach (var failure in result.Errors)
                {
                    //ModelState.AddModelError(failure.ErrorCode, failure.ErrorMessage);
                    ModelState.AddModelError(failure.PropertyName, failure.ErrorMessage);
                }
                return View(actor);
            }

            await _actorsService.Send(new UpdateActor { Id = id, actors = actor});

            return RedirectToAction(nameof(Index));

        }
        public async Task<IActionResult> Delete(int id)
        {
            var query = new GetActorById { Id = id };
            var newGetActorByIdValidator = new GetActorByIdValidator(id);
            var result = await newGetActorByIdValidator.ValidateAsync(query);

            if (!result.IsValid)
            {
                return RedirectToAction(nameof(Index));
            }
            var actorDetails = await _actorsService.Send(query);

            if (actorDetails == null)
            {
                return RedirectToAction(nameof(NotFound));

            }
            return View(actorDetails);

        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)

        {
            
            

            await _actorsService.Send(new DeleteActor { Id = id });

            return View("NotFound");

        }
    }
}

Controllers/CinemasController.cs
using Ecommerce.Data;
using Ecommerce.Data.RequestHandlers.CinemaRequestHandler;
using Ecommerce.Models;
using Ecommerce.Models.Validators.CinemaValidator;
using FluentValidation.Results;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Ecommerce.Controllers
{
    public class CinemasController : Controller
    {
        private readonly ISender _cinemaService;
        public CinemasController(ISender cinemaService)
        {
            _cinemaService = cinemaService;

        }
        
        public async Task<IActionResult> Index()
        {
           var cinemas = await _cinemaService.Send(new GetCinema());
           return View(cinemas);
        }

        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Cinema cinema)

        {
            CinemaValidator producerValidator = new CinemaValidator();
            ValidationResult result = await producerValidator.ValidateAsync(cinema);
            if (!result.IsValid)
            {
                foreach (var failure in result.Errors)
                {
                    //ModelState.AddModelError(failure.ErrorCode, failure.ErrorMessage);
                    ModelState.AddModelError(failure.PropertyName, failure.ErrorMessage);
                }
                return View(cinema);
            }

            await _cinemaService.Send(new AddCinema { cinema = cinema});

            return RedirectToAction(nameof(Index));

        }


        public async Task<IActionResult> Details(int id)
        {
            var getCinema = new GetCinemaById { Id = id };
            
            

            
            var cinemaDetails = await _cinemaService.Send(getCinema);

            if (cinemaDetails == null)
            {
                return RedirectToAction(nameof(Index));

            }
            return View(cinemaDetails);

        }

        public async Task<IActionResult> Edit(int id)
        {
            var query = new GetCinemaById { Id = id };
            var newGetCinemaByIdValidator = new GetCinemaByIdValidator(id);
            var result = await newGetCinemaByIdValidator.ValidateAsync(query);

            if (!result.IsValid)
            {
                return RedirectToAction(nameof(NotFound));
            }
            var cinema = await _cinemaService.Send(query);

            if (cinema == null)
            {
                return RedirectToAction(nameof(Index));

            }
            return View(cinema);

        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, Cinema cinema)

        {
            CinemaValidator cinemaValidator = new CinemaValidator();
            ValidationResult result = await cinemaValidator.ValidateAsync(cinema);
            if (!result.IsValid)
            {
                foreach (var failure in result.Errors)
                {
                    //ModelState.AddModelError(failure.ErrorCode, failure.ErrorMessage);
                    ModelState.AddModelError(failure.PropertyName, failure.ErrorMessage);
                }
                return View(cinema);
            }

            await _cinemaService.Send(new UpdateCinema { Id = id, cinema = cinema });

            return RedirectToAction(nameof(Index));

        }
        public async Task<IActionResult> Delete(int id)
        {
            var query = new GetCinemaById { Id = id };
            var newGetCinemaById = new GetCinemaByIdValidator(id);
            var result = await newGetCinemaById.ValidateAsync(query);

            if (!result.IsValid)
            {
                return RedirectToAction(nameof(Index));
            }
            var cinemaDetails = await _cinemaService.Send(query);

            if (cinemaDetails == null)
            {
                return RedirectToAction(nameof(NotFound));

            }
            return View(cinemaDetails);

        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)

        {
            await _cinemaService.Send(new DeleteCinema { Id = id });

            return View("NotFound");

        }

    }
}

Controllers/MoviesController.cs
using Ecommerce.Data;
using Ecommerce.Data.RequestHandlers.CinemaRequestHandler;
using Ecommerce.Data.RequestHandlers.MoviesRequestHandlers;
using Ecommerce.Data.ViewModel;
using Ecommerce.Models;
using Ecommerce.Models.Validators.ModelViewValidators;
using Ecommerce.Models.Validators.ProducerValidator;
using FluentValidation.Results;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;

namespace Ecommerce.Controllers
{
    public class MoviesController : Controller
    {
        private readonly ISender _movieServcie;
        public MoviesController(ISender movieServcie)
        {
            _movieServcie = movieServcie;
        }

        //private readonly dbContext _context;
        //public MoviesController(dbContext context)
        //{
        //    _context = context;

        //}
        public async Task<IActionResult> Index()
        {
            //var movies = await _context.Movie.Include(n => n.Cinema).OrderBy(n => n.Name).ToListAsync();
            //return View(movies);
            var movie= await _movieServcie.Send(new GetMovies());
            return View(movie);

        }
         public async Task<IActionResult> Filter(string searchString)
        {
            //var movies = await _context.Movie.Include(n => n.Cinema).OrderBy(n => n.Name).ToListAsync();
            //return View(movies);
            var movie= await _movieServcie.Send(new GetMovies());

            if (!string.IsNullOrEmpty(searchString))
            {

                var filteredResults = movie.Where(n => n.Name.Contains(searchString) || n.Description.Contains(searchString)).ToList();
                if (filteredResults.IsNullOrEmpty())
                {
                    return View("NotFound");
                }
                else
                {
                    return View("Index", filteredResults);
                }

            }
            return View("Index", movie);
        }

        public async Task<IActionResult> Details(int id)
        {
            var getMovie = new GetMovieById { Id = id };
            var movieDetails = await _movieServcie.Send(getMovie);

            if (movieDetails == null)
            {
                return RedirectToAction(nameof(Index));

            }
            return View(movieDetails);

        }
        public async Task<IActionResult> Create()
        {
            var movieDropDownData = await _movieServcie.Send(new MovieDropDown());

            ViewBag.Cinemas = new SelectList(movieDropDownData.Cinemas, "Id", "Name");
            ViewBag.Producers = new SelectList(movieDropDownData.Producers, "Id", "FullName");
            ViewBag.Actors = new SelectList(movieDropDownData.Actors, "Id", "FullName");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(MovieVM movie)
        {
            movieVmValidators movieVMValidator = new movieVmValidators();
            ValidationResult result = await movieVMValidator.ValidateAsync(movie);

            if (!result.IsValid) {
                foreach (var failure in result.Errors)
                {
                    var movieDropDownData = await _movieServcie.Send(new MovieDropDown());

                    ViewBag.Cinemas = new SelectList(movieDropDownData.Cinemas, "Id", "Name");
                    ViewBag.Producers = new SelectList(movieDropDownData.Producers, "Id", "FullName");
                    ViewBag.Actors = new SelectList(movieDropDownData.Actors, "Id", "FullName");
                    //ModelState.AddModelError(failure.ErrorCode, failure.ErrorMessage);
                    ModelState.AddModelError(failure.PropertyName, failure.ErrorMessage);
                }
                return View(movie);

            }

            await _movieServcie.Send(new AddMovie { data = movie });
            return RedirectToAction("Index");
        }
         public async Task<IActionResult> Edit(int id)
        {
            var getMovie = new GetMovieById { Id = id };
            var movieDetails = await _movieServcie.Send(getMovie);

            if (movieDetails == null)
            {
                return RedirectToAction(nameof(Index));

            }

            var response = new MovieVM()
            {
                Id = movieDetails.Id,
                Name = movieDetails.Name,
                Description = movieDetails.Description,
                Price = movieDetails.Price,
                StartDate = movieDetails.StartDate,
                EndDate = movieDetails.EndDate,
                ImageURL = movieDetails.ImageURL,
                MovieCategory = movieDetails.MovieCategory,
                CinemaId = movieDetails.CinemaId,
                ProducerId = movieDetails.ProducerId,
                ActorIds = movieDetails.Actor_Movies.Select(n => n.ActorId).ToList(),
            };

            var movieDropDownData = await _movieServcie.Send(new MovieDropDown());

            ViewBag.Cinemas = new SelectList(movieDropDownData.Cinemas, "Id", "Name");
            ViewBag.Producers = new SelectList(movieDropDownData.Producers, "Id", "FullName");
            ViewBag.Actors = new SelectList(movieDropDownData.Actors, "Id", "FullName");
            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int Id,MovieVM movie)
        {
            if (Id != movie.Id) return View("NotFound");

            movieVmValidators movieVMValidator = new movieVmValidators();
            ValidationResult result = await movieVMValidator.ValidateAsync(movie);

            if (!result.IsValid) {
                foreach (var failure in result.Errors)
                {
                    var movieDropDownData = await _movieServcie.Send(new MovieDropDown());

                    ViewBag.Cinemas = new SelectList(movieDropDownData.Cinemas, "Id", "Name");
                    ViewBag.Producers = new SelectList(movieDropDownData.Producers, "Id", "FullName");
                    ViewBag.Actors = new SelectList(movieDropDownData.Actors, "Id", "FullName");
                    //ModelState.AddModelError(failure.ErrorCode, failure.ErrorMessage);
                    ModelState.AddModelError(failure.PropertyName, failure.ErrorMessage);
                }
                return View(movie);

            }

            await _movieServcie.Send(new UpdateMovie { data = movie });
            return RedirectToAction("Index");
        }

    }
}

Views/Shared/_CreateItem.cshtml
@model string;

<div style="position: fixed; right: 25px; bottom: 25px;" class="text-white">
    <a asp-controller="@Model" asp-action="Create" class="btn btn-success">
        <i class="bi bi-plus-circle"></i> Add New
    </a>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ecommerce</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Ecommerce.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Movies" asp-action="Index">Ecommerce</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-danger" asp-controller="Movies" asp-action="Index"><i class="badge-info bi-film"></i>Movies</a>
                        </li>
                        
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                        
                        <i class="bi bi-gear"></i> Management
                        </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-controller="Cinemas" asp-action="Index"> <i class="bi bi-camera-reels"></i> Cinemas</a>
                                <a class="dropdown-item" asp-controller="Producers" asp-action="Index"> <i class="bi bi-headset"></i> Producers</a>
                                <a class="dropdown-item" asp-controller="Actors" asp-action="Index"> <i class="bi bi-person-square"></i> Actors</a>
                        </div>
                        </li>
                    </ul>
                    
                    <form class="form-inline my-2 my-lg-0" asp-controller="Movies" asp-action="Filter" style="padding-right: 25px;">
                        <div class="input-group rounded">
                        <input name="searchString" type="text" class="form-control" placeholder="Search for a movie..." aria-label="Recipient's username" aria-describedby="button-addon2">
                        <button class="btn-outline-success " type="submit"><i class="bi bi-search"></i></button></div>
                        </form>
                    
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Ecommerce 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>